project: Earning Day Stock Prediction

paths:
  data:
    directories:
      external: 
        description: External data sources (e.g., news sentiment, weather, etc.)
        path: "{data_directory}/00_external"
      raw: 
        description: Raw, unprocessed data (e.g., CSV, raw stock prices)
        path: "{data_directory}/01_raw"
      interim: 
        description: Intermediate data after initial cleaning or transformations
        path: "{data_directory}/02_interim"
      processed: 
        description: Final, cleaned, and feature-engineered dataset for modeling
        path: "{data_directory}/03_processed"


files:
  external:
    - name: "sp500_constituent.csv"  
  raw:
    - metric: 
          name: "key_metrics.csv"
    - ratios: "ratios.csv"
    - stock: "stock_hist.csv"

  interim:
    - name: "growth.csv"
    - name: "ratios.csv"
    - name: "stock_hist.csv"

  processed:
    - name: "database.csv"


variables:
  data_directory: "02_data"
